<script setup>
import {computed,ref,reactive,watch,nextTick} from 'vue'
import {message} from 'ant-design-vue'
import {ui,db,rows,task,original,publish,createTask,log} from './store'
import Icon from './Icon.vue'
import ReviewDrawer from './ReviewDrawer.vue'
import UploadDrawer from './UploadDrawer.vue'
import RulesView from './RulesView.vue'
const current=computed(task), list=computed(rows)
const reviewed=computed(()=>list.value.filter(r=>r.status==='已复核'))
const stats=computed(()=>[{name:'本次应交',value:list.value.length,unit:'人',icon:'TeamOutlined',hint:current.value.className+' · 当前任务'},{name:'已收作文',value:list.value.filter(r=>r.status!=='未提交').length,unit:'篇',icon:'InboxOutlined',hint:'学生拍照与老师上传'},{name:'待教师复核',value:list.value.filter(r=>r.status==='待复核').length,unit:'篇',icon:'FormOutlined',hint:'AI 初评已完成'},{name:'已发布反馈',value:list.value.filter(r=>r.published).length,unit:'篇',icon:'CheckCircleOutlined',hint:'学生 App 已同步可见'}])
const search=ref(''),filter=ref('全部状态'),reviewId=ref(null),upload=ref(false),newTask=ref(false),detail=ref(false)
const form=reactive({title:'',className:'中四 A 班',genre:'记叙文',due:'2026-10-08',ruleId:'dse-2025',description:'',requirements:''})
const visibleRows=computed(()=>list.value.filter(r=>(!search.value||r.student.name.includes(search.value)||r.student.number.includes(search.value))&&(filter.value==='全部状态'||r.status===filter.value)).filter(r=>ui.menu==='成绩与反馈'?['已复核','已发布'].includes(r.status):true))
const columns=[{title:'学生',dataIndex:'student',width:175},{title:'提交来源',dataIndex:'source'},{title:'页数 / 字数',key:'words'},{title:'处理状态',dataIndex:'status'},{title:'成绩',key:'score'},{title:'操作',key:'actions',width:190}]
watch(()=>ui.menu,()=>{filter.value='全部状态';search.value=''})
const statusColor=s=>({'待复核':'blue','已发布':'green','已复核':'cyan','需补交':'orange','未提交':'default'}[s]||'processing')
function openReview(r){reviewId.value=r.id}
function release(r){try{publish(original(r.id));message.success('成绩已发布，学生 App 可查看')}catch(e){message.warning(e.message)}}
function releaseAll(){if(!reviewed.value.length)return message.info('暂无已复核待发布的作文'); reviewed.value.forEach(r=>publish(original(r.id)));message.success('已发布全部复核完成的作文')}
function saveTask(){if(!form.title.trim()||!form.description.trim()||!form.requirements.trim()||!form.due)return message.warning('请填写题目、写作要求、截止日期和审题要求');createTask({...form,title:form.title.trim()});newTask.value=false;ui.menu='收稿管理';message.success('任务已发布，学生 App 已可见')}
function goApp(r){ui.studentId=r.studentId;ui.tab='app';nextTick(()=>{ui.appDetail=true})}
const isAdmin=computed(()=>ui.role==='学校管理员')
const headings={'工作台':['上午好，王老师','把更多时间留给写作教学，让每一份反馈都有依据。'],'作文任务':['作文任务','题目、收稿、批改和反馈，在同一个任务中完成。'],'收稿管理':['收稿管理','汇总两种提交入口，确认每一页作文的归属。'],'批改中心':['批改中心','对照原稿复核，让每一个评分判断都有依据。'],'成绩与反馈':['成绩与反馈','教师复核后发布，学生才能看到正式结果。'],'教学组织':['教学组织','学生身份持续保留，班级与班号按学年管理。'],'学校设置':['学校设置','学校管理员负责组织与权限，不默认拥有改分权限。'],'学情分析':['学情分析','同一任务、同一标准下查看学生表现。']}
const head=computed(()=>headings[ui.menu]||[ui.menu,''])
</script>
<template>
<RulesView v-if="ui.menu==='评分标准'" embedded/>
<template v-else>
 <div class="page-head"><div><div class="eyebrow">教学管理 / {{ui.menu}}</div><h1>{{head[0]}}<span v-if="ui.menu==='工作台'" class="hello-dot">✦</span></h1><p>{{head[1]}}</p></div><a-space v-if="!isAdmin"><a-button @click="upload=true" v-if="ui.role==='任课教师'"><Icon name="UploadOutlined"/>批量上传</a-button><a-button v-if="ui.role==='任课教师'" type="primary" @click="newTask=true"><Icon name="PlusOutlined"/>新建作文任务</a-button></a-space></div>
 <template v-if="isAdmin">
  <div class="stats"><div v-for="s in [{name:'当前学年',value:'2026/27'},{name:'教学班级',value:1},{name:'在读学生',value:db.students.length},{name:'任课教师',value:1}]" class="stat-card"><p>{{s.name}}</p><div class="stat-number">{{s.value}}</div></div></div>
  <div v-if="ui.menu!=='学校设置'" class="panel"><div class="panel-head"><h2>中四 A 班 · 学生名单</h2><a-tag>2026—2027 学年</a-tag></div><a-table :data-source="db.students" :columns="[{title:'姓名',dataIndex:'name'},{title:'所在班级',dataIndex:'className'},{title:'班号',dataIndex:'number'},{title:'稳定学生 ID',dataIndex:'id'}]" row-key="id" :pagination="{pageSize:6}"/><a-alert message="班号按学年管理，学生身份持续关联历史作文。" type="info" show-icon/></div>
  <div v-else class="panel"><h2>角色权限说明</h2><a-descriptions bordered :column="1" style="margin-top:20px"><a-descriptions-item label="学校管理员">管理账号、学年、班级及任课关系</a-descriptions-item><a-descriptions-item label="教学负责人">审核评分方案，查看授权范围教学表现</a-descriptions-item><a-descriptions-item label="任课教师">创建任务、收稿、复核和发布</a-descriptions-item><a-descriptions-item label="学生">仅提交本人任务、查看本人已发布结果</a-descriptions-item></a-descriptions><a-alert style="margin-top:20px" message="角色权限由学校统一管理，操作范围以任课关系为准。" type="info" show-icon/></div>
 </template>
 <template v-else>
  <div class="stats"><div v-for="s in stats" :key="s.name" class="stat-card"><div class="stat-label">{{s.name}}<Icon :name="s.icon"/></div><div class="stat-number">{{s.value}}<small>{{s.unit}}</small></div><p>{{s.hint}}</p></div></div>
  <div v-if="ui.menu==='工作台'" class="dashboard-grid">
   <div class="panel active-task"><div class="panel-head"><div><h2>正在进行的作文</h2><p>2026 秋季 · 写作训练</p></div><a-button type="link" @click="ui.menu='作文任务'">全部任务 <Icon name="ArrowRightOutlined"/></a-button></div><div class="task-feature"><div class="essay-icon"><Icon name="FileTextOutlined"/></div><div><a-tag color="blue">{{current.genre}}</a-tag><a-tag>当前任务</a-tag><h2>{{current.title}}</h2><p>{{current.className}}<span>·</span>截止 {{current.due}}</p></div></div><div class="progress-meta"><span>收稿进度</span><strong>{{stats[1].value}} / {{stats[0].value}} 篇</strong></div><a-progress :percent="Math.round(stats[1].value/stats[0].value*100)" :show-info="false" stroke-color="#3557cf" :stroke-width="7"/><div class="task-bottom"><span><Icon name="SafetyCertificateOutlined"/> {{current.rule.name}}</span><a-button type="primary" @click="ui.menu='批改中心'">进入批改 <Icon name="ArrowRightOutlined"/></a-button></div></div>
   <div class="panel todo-panel"><h2>需要你处理</h2><button class="todo-item" @click="ui.menu='批改中心';filter='待复核'"><span class="todo-icon blue"><Icon name="FormOutlined"/></span><div><strong>复核 AI 初评</strong><small>确认评分依据与原稿批注</small></div><b>{{stats[2].value}}</b><Icon name="RightOutlined"/></button><button class="todo-item" @click="ui.menu='收稿管理';filter='需补交'"><span class="todo-icon amber"><Icon name="FileExclamationOutlined"/></span><div><strong>检查异常稿件</strong><small>缺页或图片不清晰</small></div><b>{{list.filter(r=>r.status==='需补交').length}}</b><Icon name="RightOutlined"/></button><button class="todo-item" @click="ui.menu='成绩与反馈';filter='已复核'"><span class="todo-icon green"><Icon name="SendOutlined"/></span><div><strong>发布成绩反馈</strong><small>已完成教师复核</small></div><b>{{reviewed.length}}</b><Icon name="RightOutlined"/></button></div>
  </div>
  <div v-if="ui.menu==='作文任务'" class="task-grid"><div v-for="t in db.tasks" :key="t.id" class="panel task-tile"><div class="panel-head"><a-tag color="blue">{{t.status}}</a-tag><span class="muted">{{t.className}}</span></div><h2>{{t.title}}</h2><p>{{t.description}}</p><div class="muted">截止 {{t.due}} · {{t.rule.version}}</div><a-space style="margin-top:20px"><a-button type="primary" @click="ui.taskId=t.id;ui.menu='收稿管理';filter='全部状态'">进入任务</a-button><a-button @click="ui.taskId=t.id;detail=true">任务要求</a-button></a-space></div></div>
  <div v-else-if="ui.menu==='学情分析'" class="panel"><div class="panel-head"><h2>已发布作文表现</h2><a-tag color="blue">{{current.rule.name}}</a-tag></div><a-empty v-if="!list.some(r=>r.published)" description="发布成绩后生成本任务表现"/><div v-for="r in list.filter(r=>r.published)" class="analysis-row"><span>{{r.student.name}}</span><a-progress :percent="Math.round(r.published.total/r.published.max*100)" :format="()=>`${r.published.total} / ${r.published.max}`"/></div><a-alert message="只比较当前任务、同一评分方案的已发布成绩；不推算 DSE 总科等级。" type="info" show-icon/></div>
  <div v-else class="panel roster-panel">
   <div class="panel-head"><div><h2>{{ui.menu==='成绩与反馈'?'成绩发布':ui.menu==='工作台'?'最近提交':'学生稿件'}}<span class="count-pill">{{visibleRows.length}}</span></h2><p>{{current.title}} · {{current.className}}</p></div><a-space><a-select v-if="db.tasks.length>1" v-model:value="ui.taskId" :options="db.tasks.map(t=>({value:t.id,label:t.title}))" style="min-width:170px"/><a-button v-if="ui.menu==='成绩与反馈' && ui.role==='任课教师'" type="primary" :disabled="!reviewed.length" @click="releaseAll">发布已复核（{{reviewed.length}}）</a-button><a-button v-else @click="detail=true">任务要求</a-button></a-space></div>
   <div class="table-tools"><a-input v-model:value="search" placeholder="搜索学生姓名或班号" allow-clear style="width:240px"><template #prefix><Icon name="SearchOutlined"/></template></a-input><a-select v-model:value="filter" style="width:145px" :options="['全部状态','未提交','待复核','已复核','已发布','需补交'].map(x=>({value:x,label:x}))"/><span class="table-hint">两种提交方式 · 统一收稿</span></div>
   <a-table :data-source="visibleRows" :columns="columns" row-key="id" :pagination="{pageSize:6,showTotal:total=>`共 ${total} 位学生`,showSizeChanger:false}" :scroll="{x:800}">
    <template #bodyCell="{column,record}">
     <template v-if="column.dataIndex==='student'"><div class="student-cell"><a-avatar :style="{background:record.studentId%2?'#edf0ff':'#e9f4f4',color:record.studentId%2?'#6073bb':'#648e8b'}">{{record.student.name.slice(-2)}}</a-avatar><div><strong>{{record.student.name}}</strong><small>{{record.student.number}}号 · {{record.student.className}}</small></div></div></template>
     <template v-if="column.dataIndex==='source'"><span class="source-cell"><Icon :name="record.source==='学生拍照'?'MobileOutlined':'UploadOutlined'"/>{{record.source}}</span></template>
     <template v-if="column.key==='words'"><span v-if="record.pages">{{record.pages}} 页 <span class="muted">/ {{record.input.words}} 字</span></span><span v-else class="muted">—</span></template>
     <template v-if="column.dataIndex==='status'"><a-tag :color="statusColor(record.status)">{{record.status}}</a-tag></template>
     <template v-if="column.key==='score'"><strong v-if="record.published">{{record.published.total}}<small class="muted"> / {{record.published.max}}</small></strong><strong v-else-if="record.review">{{record.review.total}}<small class="muted"> 待发布</small></strong><span v-else class="muted">—</span></template>
     <template v-if="column.key==='actions'"><a-space :size="3"><a-button v-if="['待复核','已复核','已发布'].includes(record.status)&&ui.role==='任课教师'" type="link" size="small" @click="openReview(record)">{{record.status==='已发布'?'查看 / 复核':'复核作文'}}</a-button><a-button v-if="record.status==='已复核'&&ui.role==='任课教师'" type="link" size="small" @click="release(record)">发布</a-button><a-button v-if="record.status==='已发布'" type="link" size="small" @click="goApp(record)">App 查看</a-button><a-button v-if="['需补交','未提交'].includes(record.status)&&ui.role==='任课教师'" type="link" size="small" @click="upload=true">{{record.status==='需补交'?'补齐原稿':'上传原稿'}}</a-button></a-space></template>
    </template>
   </a-table>
  </div>
  <div v-if="ui.menu==='工作台'" class="activity-line"><Icon name="HistoryOutlined"/><span>{{db.logs[0]?.at}}</span>{{db.logs[0]?.text}}<a-button type="link" size="small" @click="ui.tab='flow'">查看业务流程</a-button></div>
 </template>
</template>
<ReviewDrawer v-if="reviewId" :id="reviewId" @close="reviewId=null"/>
<UploadDrawer v-if="upload" @close="upload=false"/>
<a-modal v-model:open="newTask" title="新建作文任务" width="650px" ok-text="确认并发布任务" cancel-text="取消" @ok="saveTask"><a-alert style="margin:16px 0" message="发布后固定本次评分方案，学生 App 将显示新任务。" type="info" show-icon/><a-form layout="vertical"><a-form-item label="作文题目" required><a-input v-model:value="form.title" placeholder="例如：为不完美添色彩" :maxlength="60"/></a-form-item><div class="form-grid"><a-form-item label="班级"><a-select v-model:value="form.className" :options="[{value:'中四 A 班',label:'中四 A 班'}]"/></a-form-item><a-form-item label="文体"><a-select v-model:value="form.genre" :options="['记叙文','议论文','文体不限'].map(x=>({value:x,label:x}))"/></a-form-item></div><div class="form-grid"><a-form-item label="截止日期" required><a-input type="date" v-model:value="form.due"/></a-form-item><a-form-item label="评分方案"><a-select v-model:value="form.ruleId" :options="db.rules.map(r=>({value:r.id,label:r.name}))"/></a-form-item></div><a-form-item label="写作要求（学生可见）" required><a-textarea v-model:value="form.description" :rows="3" placeholder="题干、材料和关键字数要求"/></a-form-item><a-form-item label="审题与入品要求（教师确认）" required><a-textarea v-model:value="form.requirements" :rows="3" placeholder="明确题意、合理诠释范围与取材要求"/></a-form-item></a-form></a-modal>
<a-drawer v-model:open="detail" title="任务要求与评分快照" width="560"><a-tag color="blue">{{current.genre}}</a-tag><h2>{{current.title}}</h2><p class="drawer-copy">{{current.description}}</p><a-descriptions bordered :column="1"><a-descriptions-item label="班级">{{current.className}}</a-descriptions-item><a-descriptions-item label="截止">{{current.due}}</a-descriptions-item><a-descriptions-item label="固定评分方案">{{current.rule.name}} · {{current.rule.version}}</a-descriptions-item><a-descriptions-item label="审题要求">{{current.requirements}}</a-descriptions-item><a-descriptions-item label="提交方式">学生拍照 / 老师批量上传</a-descriptions-item></a-descriptions><a-alert style="margin-top:24px" message="发布反馈后任务结束，不设置重写或订正提交。" type="info" show-icon/></a-drawer>
</template>
