<script setup>
import {ref,computed} from 'vue'
import Icon from './Icon.vue'
const active=ref('学生拍照提交'),selected=ref(0)
const flows={
 '学生拍照提交':[{role:'教师',title:'发布作文任务',note:'选择班级、题目与评分方案，发布时锁定评分快照。',icon:'FileAddOutlined'},{role:'学生 App',title:'拍照并提交',note:'进入任务，拍摄多页作文，确认清晰度及页序。',icon:'CameraOutlined'},{role:'系统',title:'检查与收稿',note:'校验归属、图片完整性和重复提交，返回收稿回执。',icon:'InboxOutlined'},{role:'AI',title:'识别与分项初评',note:'识别文字，按题意与方案评价各维度，给出原文依据。',icon:'ReadOutlined'},{role:'规则引擎',title:'执行计分规则',note:'计算字数、错字分档及维度上限，标记边界问题。',icon:'CalculatorOutlined'},{role:'教师',title:'复核并发布',note:'核对原稿与评分，处理异常后发布正式成绩。',icon:'CheckCircleOutlined'},{role:'学生 App',title:'查看成绩反馈',note:'查看分项成绩、原文批注与改进建议，本次任务完成。',icon:'SolutionOutlined'}],
 '老师批量上传':[{role:'教师',title:'选择任务与班级',note:'进入任务收稿名单，批量上传照片或扫描文件。',icon:'TeamOutlined'},{role:'系统',title:'分组与身份匹配',note:'根据班号、姓名及页码提出分组，标记冲突和缺页。',icon:'ApartmentOutlined'},{role:'教师',title:'确认稿件归属',note:'确认学生与页序，处理未匹配和重复稿件。',icon:'UserSwitchOutlined'},{role:'AI',title:'识别与分项初评',note:'仅处理归属已确认的稿件，保留原图定位和评分证据。',icon:'ReadOutlined'},{role:'规则引擎',title:'执行计分规则',note:'执行维度上限和总分计算，异常进入复核队列。',icon:'CalculatorOutlined'},{role:'教师',title:'复核并发布',note:'逐篇确认后发布，批量发布仅包含已完成复核的结果。',icon:'CheckCircleOutlined'},{role:'学生 App',title:'查看成绩反馈',note:'老师上传后显示已收稿，无需学生重复提交。',icon:'SolutionOutlined'}],
 '异常与评分修订':[{role:'教师 / 系统',title:'发现异常',note:'发现缺页、图片模糊、身份冲突、识别或评分问题。',icon:'WarningOutlined'},{role:'教师',title:'判断异常类型',note:'提交问题回到原稿确认；评分问题进入复核。',icon:'BranchesOutlined'},{role:'教师 / 学生',title:'补齐或纠正原稿',note:'补交指定页、替换清晰图片或修正身份，不改变作文创作内容。',icon:'FileSyncOutlined'},{role:'系统',title:'更新受影响结果',note:'记录技术修订，重新识别或计算依赖项，旧结果不被静默覆盖。',icon:'SyncOutlined'},{role:'教师',title:'复核修订',note:'确认分项评价及原因，解决边界问题。',icon:'FormOutlined'},{role:'教师',title:'重新发布',note:'若原结果已发布，保留历史并将新结果设为当前正式成绩。',icon:'SendOutlined'},{role:'学生 App',title:'查看更新反馈',note:'提示成绩更新，展示当前正式结果；不增加重写入口。',icon:'BellOutlined'}]
}
const nodes=computed(()=>flows[active.value]);function choose(v){active.value=v;selected.value=0}
</script>
<template><main class="wide-page flow-page"><div class="page-head"><div><div class="eyebrow">业务流程</div><h1>从收稿，到每一份反馈</h1><p>学校制定标准，老师组织教学，AI 辅助评阅，学生查看反馈。</p></div><a-tag color="blue">教师复核后发布</a-tag></div><div class="role-strip"><div v-for="r in [{name:'学校管理员',icon:'BankOutlined',text:'组织与权限'},{name:'教学负责人',icon:'SafetyCertificateOutlined',text:'标准与校准'},{name:'任课教师',icon:'UserOutlined',text:'任务、复核与发布'},{name:'学生',icon:'MobileOutlined',text:'拍照提交与查看'},{name:'AI 与规则服务',icon:'ApiOutlined',text:'初评与确定性计算'}]"><span><Icon :name="r.icon"/></span><h3>{{r.name}}</h3><p>{{r.text}}</p></div></div><div class="panel flow-panel"><div class="flow-selector"><button v-for="key in Object.keys(flows)" :class="{active:active===key}" @click="choose(key)">{{key}}</button></div><div class="flow-legend"><span><i class="blue-dot"></i>人工操作</span><span><i class="purple-dot"></i>系统处理</span><small>点击节点查看执行要求</small></div><div class="flow-canvas"><template v-for="(n,i) in nodes" :key="n.title"><button class="flow-node" :class="{selected:selected===i,system:['AI','系统','规则引擎'].includes(n.role)}" @click="selected=i"><span class="flow-order">0{{i+1}}</span><span class="flow-node-icon"><Icon :name="n.icon"/></span><small>{{n.role}}</small><strong>{{n.title}}</strong></button><span v-if="i<nodes.length-1" class="flow-arrow"><Icon name="ArrowRightOutlined"/></span></template></div><div class="node-detail"><div class="node-number">0{{selected+1}}</div><div><span>{{nodes[selected].role}}</span><h3>{{nodes[selected].title}}</h3><p>{{nodes[selected].note}}</p></div><a-tag>操作要求</a-tag></div></div><div class="flow-bottom"><div class="panel"><h2>两种入口，同一份成绩</h2><div class="merge-diagram"><span>学生拍照</span><span>老师批量上传</span><b>↓</b><strong>统一收稿 · 学生匹配 · 重复检查</strong><b>↓</b><strong>同一评分方案 · 同一正式结果</strong></div></div><div class="panel"><h2>角色操作边界</h2><div class="permission-row"><span>学校管理员</span><p>管理学校、账号和任课关系，不默认拥有改分权限。</p></div><div class="permission-row"><span>教师</span><p>仅处理授权班级；确认稿件、评分依据和最终发布。</p></div><div class="permission-row"><span>学生</span><p>仅查看本人任务与已发布反馈，不能查看 AI 初评草稿。</p></div><div class="permission-row"><span>AI</span><p>提供评价建议，无独立发布权限。</p></div></div></div></main></template>
