<script setup>
import {reactive,computed,ref} from 'vue'
import {message} from 'ant-design-vue'
import {dse,bands,calculate} from './scoring'
import {db,log} from './store'
import Icon from './Icon.vue'
defineProps({embedded:Boolean})
const section=ref('评分总览'),selected=ref('dse-2025'),customOpen=ref(false)
const rule=computed(()=>db.rules.find(r=>r.id===selected.value)||dse)
const input=reactive({words:520,typos:2,content:9,expression:8,structure:7,writing:8,offTopic:false})
const result=computed(()=>calculate(input,rule.value))
const form=reactive({name:'中四记叙文 · 校本方案',grade:'中四',wordLimit:500,content:40,expression:30,structure:20,writing:10,description:'内容：围绕题意，选材具体；表达：准确流畅；结构：详略恰当；标点字体：清晰规范。'})
const maxima=computed(()=>form.content+form.expression+form.structure+form.writing)
function save(){if(!form.name.trim()||!form.description.trim())return message.warning('请填写方案名称和档位说明');if(maxima.value!==100)return message.warning('此校本模板各维度须合计100分');const r={id:'school-'+Date.now(),name:form.name,grade:form.grade,description:form.description,wordLimit:form.wordLimit,type:'school',version:'v1.0',typoMax:0,caps:false,dimensions:dse.dimensions.map(d=>({...d,max:form[d.key]}))};db.rules.push(r);selected.value=r.id;customOpen.value=false;log(`教学负责人发布校本方案「${r.name}」`);message.success('校本方案已保存，新任务可选；历史任务保持原快照')}
</script>
<template><main :class="embedded?'rules-embedded':'wide-page rules-page'"><div class="page-head"><div><div class="eyebrow">评分标准</div><h1>评分标准，有据可循</h1><p>把文章评价与规则计算分开，适配不同学校和年级。</p></div><a-button type="primary" @click="customOpen=true"><Icon name="CopyOutlined"/>创建校本方案</a-button></div>
 <div class="rule-layout"><aside class="rule-sidebar"><div class="nav-label">评分方案</div><button v-for="r in db.rules" :class="{active:selected===r.id}" @click="selected=r.id"><Icon name="SafetyCertificateOutlined"/><span>{{r.name}}<small>{{r.type==='official'?'官方参考':'校本方案'}} · {{r.version}}</small></span></button><div class="rule-side-note"><Icon name="LockOutlined"/><p>任务发布时保存评分快照。更新模板不会改变历史成绩。</p></div></aside><div class="rule-main">
 <div class="rule-banner"><div><a-tag :color="rule.type==='official'?'blue':'purple'">{{rule.type==='official'?'官方参考 · 2025 年':'校本自定义'}}</a-tag><h2>{{rule.name}}</h2><p>{{rule.type==='official'?'适用于中国语文科卷二乙部命题写作，不代表所有年级通用要求。':rule.description}}</p></div><div class="rule-full"><b>{{result.max}}</b><span>满分</span></div></div>
 <a-tabs v-model:activeKey="section"><a-tab-pane key="评分总览" tab="评分总览"/><a-tab-pane key="规则试算" tab="规则试算"/><a-tab-pane key="版本与适用" tab="版本与适用"/></a-tabs>
 <template v-if="section==='评分总览'"><div class="dimension-cards"><div v-for="(d,i) in rule.dimensions" class="panel dimension-card"><span class="dimension-index">0{{i+1}}</span><h3>{{d.name}}</h3><div><b>{{d.max}}</b><span>分</span></div><p>{{['立意与取材，整体入品','词句准确、流畅与手法','层次、衔接与详略','依据原图，重视书写'][i]}}</p></div></div><div class="panel"><div class="panel-head"><h2>字数与内容上限</h2><a-tag color="orange">封顶规则 ≠ 直接扣总分</a-tag></div><a-table v-if="rule.caps" :pagination="false" :columns="[{title:'字数（包含标点）',dataIndex:'range'},{title:'内容最高品第',dataIndex:'grade'},{title:'等级值',dataIndex:'value'},{title:'实现方式',dataIndex:'note'}]" :data-source="[{key:1,range:'650字及以上',grade:'上上',value:10,note:'不触发字数上限'},{key:2,range:'550—649字',grade:'上上',value:10,note:'不自动降一档'},{key:3,range:'450—549字',grade:'中上',value:7,note:'内容等级取较低值'},{key:4,range:'300—449字',grade:'中中（下）',value:5,note:'恰好300字须确认'},{key:5,range:'原文：300字以下',grade:'下上',value:3,note:'原文件300字边界措辞重叠'}]"/><a-alert v-else message="本校本方案未启用 DSE 字数与离题封顶，也不含独立错别字加分；字数要求仅作练习提示。" type="info" show-icon/><div class="rule-formula">最终内容等级 = min（原始评价等级，适用规则上限）</div></div><div class="two-cols"><div class="panel"><h3>错别字独立计分</h3><p class="drawer-copy">0—1个：3分 · 2—4个：2分<br>5—7个：1分 · 8个及以上：0分</p><small class="muted">DSE参考：重错不重复计算；OCR识别错误不能计作学生错字。校本是否采用，以方案为准。</small></div><div class="panel"><h3>离题卷的维度上限</h3><p class="drawer-copy">内容：下上（3）<br>表达与结构：中上（7）</p><small class="muted">DSE参考：由教师确认离题；标点字体仍可上上，不整篇直接判零。</small></div></div></template>
 <template v-else-if="section==='规则试算'"><div class="calculator-grid"><div class="panel"><h2>输入作文评定</h2><p class="muted" style="margin:8px 0 22px">试算不更改任何学生成绩</p><a-form layout="vertical"><div class="form-grid"><a-form-item label="确认字数"><a-input-number v-model:value="input.words" :min="0" :precision="0" style="width:100%"/></a-form-item><a-form-item label="确认错别字数"><a-input-number v-model:value="input.typos" :min="0" :precision="0" style="width:100%"/></a-form-item></div><a-form-item v-for="d in rule.dimensions" :label="`${d.name} · 原始评定`"><a-select v-model:value="input[d.key]" :options="bands.map((b,i)=>({label:`${b}（${i}）`,value:i}))"/></a-form-item><a-checkbox v-model:checked="input.offTopic">教师确认离题（DSE方案生效）</a-checkbox></a-form><div class="scenario-buttons"><a-button size="small" @click="input.words=520;input.content=9;input.offTopic=false">520字封顶</a-button><a-button size="small" @click="input.words=300">300字边界</a-button><a-button size="small" @click="input.words=700;input.offTopic=true">离题封顶</a-button></div></div><div><div class="calculator-result"><span>规则计算结果</span><div><b>{{result.pending.length?'待确认':result.total}}</b><small v-if="!result.pending.length"> / {{result.max}}</small></div><p>保留原始评价，逐条应用计分规则</p></div><div class="panel"><div v-for="d in result.dimensions" class="result-row"><div><strong>{{d.name}}</strong><small>{{bands[d.raw]}} → {{bands[d.final]}}</small></div><b>{{d.score}} <small>/ {{d.max}}</small></b></div><div class="result-row"><span>错别字独立计分</span><b>{{result.typoScore}} / {{rule.typoMax}}</b></div><a-alert v-for="p in result.pending" :message="p" type="warning" show-icon/><div class="rule-log"><strong>计算说明</strong><p v-for="r in result.adjustments">{{r}}</p><p v-if="!result.adjustments.length">未触发封顶规则。</p><p v-if="result.pending.length">分项结果仅供复核，待确认前不形成可发布总分。</p></div></div></div></div></template>
 <template v-else><div class="panel"><h2>方案的生命周期</h2><a-steps style="margin:30px 0" :current="2" :items="[{title:'草稿'},{title:'审核'},{title:'发布'},{title:'停用'}]"/><a-descriptions :column="1" bordered><a-descriptions-item label="当前版本">{{rule.version}} · {{rule.name}}</a-descriptions-item><a-descriptions-item label="来源">{{rule.type==='official'?'考评局2025年教师会议简报，第4—9页':'学校教学负责人制定'}}</a-descriptions-item><a-descriptions-item label="变更规则">修改后建立新版本；可创建并发布新的校本方案。</a-descriptions-item><a-descriptions-item label="历史任务">引用发布时快照，不随模板变化。</a-descriptions-item><a-descriptions-item label="待确认口径">标题、英文、数字、涂改字数口径；恰好300字边界。</a-descriptions-item></a-descriptions></div></template>
 <a class="source-link" href="https://www.hkeaa.edu.hk/DocLibrary/HKDSE/Subject_Information/chi_lang/CHI-BS-2025-3.pdf#page=4" target="_blank" rel="noopener"><Icon name="LinkOutlined"/> 参考来源：香港考评局 2025 年卷二乙部教师会议简报</a>
 </div></div>
 <a-modal v-model:open="customOpen" title="创建校本评分方案" ok-text="保存为可选方案" cancel-text="取消" @ok="save" width="650"><a-alert style="margin:16px 0" message="此校本模板采用四维度100分，不继承DSE封顶或独立错字分。不会改变已发布任务。" type="info" show-icon/><a-form layout="vertical"><a-form-item label="方案名称" required><a-input v-model:value="form.name"/></a-form-item><div class="form-grid"><a-form-item label="适用年级"><a-select v-model:value="form.grade" :options="['小三','小六','中三','中四','中六'].map(x=>({value:x,label:x}))"/></a-form-item><a-form-item label="练习建议字数"><a-input-number v-model:value="form.wordLimit" :min="100" :max="3000" :precision="0"/></a-form-item></div><div class="form-grid"><a-form-item v-for="d in dse.dimensions" :label="d.name+'满分'"><a-input-number v-model:value="form[d.key]" :min="1" :max="100" :precision="0" style="width:100%"/></a-form-item></div><p :class="maxima===100?'muted':'warning-text'" style="margin-bottom:16px">当前合计：{{maxima}} / 100</p><a-form-item label="档位与评价说明" required><a-textarea v-model:value="form.description" :rows="4"/></a-form-item></a-form></a-modal>
</main></template>
