<script setup>
import {computed,ref,watch} from 'vue'
import {message} from 'ant-design-vue'
import {db,ui,task,log,defaultInput} from './store'
import Icon from './Icon.vue'
const current=computed(task), student=computed(()=>db.students.find(s=>s.id===ui.studentId)), record=computed(()=>db.submissions.find(r=>r.taskId===ui.taskId&&r.studentId===ui.studentId))
const photos=ref([]),busy=ref(false),uploading=ref(false)
watch([()=>ui.studentId,()=>ui.taskId],()=>{photos.value=[];uploading.value=false;ui.appDetail=false})
const own=computed(()=>db.submissions.filter(r=>r.studentId===ui.studentId))
const canSubmit=computed(()=>['未提交','需补交'].includes(record.value?.status))
function enter(t){ui.taskId=t.id;setTimeout(()=>ui.appDetail=true,0)}
function pick(file){if(!file.type.startsWith('image/')){message.warning('请选择作文照片');return false}photos.value.push({id:Date.now()+Math.random(),name:file.name,url:URL.createObjectURL(file)});return false}
function sample(){photos.value=[{id:1,name:'作文第1页',url:null},{id:2,name:'作文第2页',url:null},{id:3,name:'作文第3页',url:null}]}
function move(i,d){const j=i+d;if(j<0||j>=photos.value.length)return;const a=photos.value.splice(i,1)[0];photos.value.splice(j,0,a)}
async function submit(){if(!photos.value.length)return message.warning('请添加作文照片');if(!canSubmit.value)return message.warning('此任务已有稿件，请勿重复提交');busy.value=true;await new Promise(r=>setTimeout(r,550));Object.assign(record.value,{status:'待复核',source:'学生拍照',pages:photos.value.length,input:defaultInput(ui.studentId),feedback:'能够扣连题意，细节还可进一步展开。',files:photos.value.map(p=>({name:p.name})),review:null});log(`${student.value.name}拍照提交，AI 初评完成`);busy.value=false;uploading.value=false;photos.value=[];message.success('提交成功，等待教师复核')}
const statusLabel=r=>r?.published?(r.status==='已复核'?'成绩已发布 · 修订待发布':'成绩已发布'):r?.status==='待复核'?'已收稿 · 等待老师反馈':r?.status||'未提交'
</script>
<template><main class="app-stage"><div class="app-explainer"><div class="eyebrow">明德书院 / 学生端</div><h1>学生工作空间</h1><p class="app-intro">2026—2027 学年 · 中文科</p><div class="app-selector"><label>学生</label><a-select v-model:value="ui.studentId" :options="db.students.map(s=>({value:s.id,label:`${s.name} · ${s.number}号`}))" style="width:100%"/><label>作文任务</label><a-select v-model:value="ui.taskId" :options="db.tasks.map(t=>({value:t.id,label:t.title}))" style="width:100%"/></div><div class="panel student-context"><h3>{{student.name}}</h3><div><span>班级</span><strong>{{student.className}}</strong></div><div><span>班号</span><strong>{{student.number}}</strong></div><div><span>收稿状态</span><a-tag :color="record.status==='未提交'?'orange':'blue'">{{statusLabel(record)}}</a-tag></div><div><span>提交来源</span><strong>{{record.source}}</strong></div><div><span>评分方案</span><strong>{{current.rule.name}}</strong></div></div></div>
 <div class="phone-wrap"><div class="phone"><div class="phone-status"><b>9:41</b><span class="dynamic-island"></span><span>▮▮▮ &nbsp; ◉ &nbsp; ▰</span></div><div class="phone-content">
 <template v-if="ui.appPage==='我的'"><div class="mobile-head"><h2>我的</h2></div><div class="mobile-profile"><a-avatar :size="65" style="background:#3557cf">{{student.name.slice(-2)}}</a-avatar><h2>{{student.name}}</h2><p>明德书院 · {{student.className}} · {{student.number}}号</p></div><div class="mobile-card"><div class="mobile-setting">当前学年 <strong>2026—2027</strong></div><div class="mobile-setting">学生账号 <strong>student{{String(student.id).padStart(4,'0')}}</strong></div><div class="mobile-setting">账号说明 <span>已绑定学校</span></div></div><p class="mobile-note">班级和班号由学校管理。历史作文持续关联同一学生身份。</p></template>
 <template v-else-if="ui.appPage==='消息'"><div class="mobile-head"><h2>消息</h2><a-tag>任务通知</a-tag></div><div v-for="r in own.filter(r=>r.published||r.status==='需补交')" class="mobile-card clickable" @click="ui.taskId=r.taskId;ui.appPage='任务';ui.appDetail=true"><span class="notice-icon"><Icon :name="r.published?'CheckCircleOutlined':'FileExclamationOutlined'"/></span><h3>{{r.published?'作文反馈已发布':'请补齐原稿图片'}}</h3><p>{{db.tasks.find(t=>t.id===r.taskId)?.title}}</p><small>{{r.published?'点击查看分项成绩与老师评语':'仅补交缺页或清晰图片，不修改作文内容'}}</small></div><a-empty v-if="!own.some(r=>r.published||r.status==='需补交')" description="暂时没有新消息"/><div class="mobile-card clickable" @click="ui.appPage='任务';ui.appDetail=false"><h3>作文任务已发布</h3><p>前往任务列表查看写作要求</p></div></template>
 <template v-else-if="!ui.appDetail"><div class="mobile-head"><div><span class="mobile-greeting">你好，{{student.name}}</span><h2>我的作文</h2></div><span class="mini-brand">中</span></div><div class="mobile-banner"><small>秋季 · 写作训练</small><h3>用文字，记录你的世界。</h3><span>{{student.className}} · {{own.length}} 个作文任务</span><Icon name="EditOutlined"/></div><div class="mobile-section-head"><h3>作文任务</h3><span>{{own.length}} 项</span></div><div v-for="t in db.tasks" :key="t.id" class="mobile-card task-mobile clickable" @click="enter(t)"><div class="mobile-row"><a-tag color="blue">{{t.genre}}</a-tag><small>{{db.submissions.find(r=>r.taskId===t.id&&r.studentId===ui.studentId)?.published?'可查看反馈':'写作训练'}}</small></div><h3>{{t.title}}</h3><p>{{t.description}}</p><div class="mobile-due"><Icon name="ClockCircleOutlined"/> 截止 {{t.due}}</div><div class="mobile-task-foot"><span>{{statusLabel(db.submissions.find(r=>r.taskId===t.id&&r.studentId===ui.studentId))}}</span><Icon name="ArrowRightOutlined"/></div></div></template>
 <template v-else><button class="mobile-back" @click="ui.appDetail=false;uploading=false"><Icon name="LeftOutlined"/> 作文任务</button><div class="mobile-detail-title"><a-tag color="blue">{{current.genre}}</a-tag><h2>{{current.title}}</h2><p>{{current.className}} · 截止 {{current.due}}</p></div>
  <template v-if="record?.published && !uploading"><div class="mobile-score"><span>老师已发布反馈</span><div><b>{{record.published.total}}</b> / {{record.published.max}}</div><small>王老师复核 · {{current.rule.name}}</small></div><div class="mobile-card"><h3>分项表现</h3><div v-for="d in record.published.dimensions" class="mobile-dimension"><span>{{d.name}}</span><a-progress :percent="d.score/d.max*100" :show-info="false" :stroke-width="5"/><strong>{{d.score}}<small>/{{d.max}}</small></strong></div><div class="mobile-row"><span>错别字</span><strong>{{record.published.typoScore}} / {{current.rule.typoMax}}</strong></div></div><div class="mobile-card"><h3><Icon name="MessageOutlined"/> 老师的反馈</h3><p class="feedback-copy">{{record.published.feedback}}</p></div><div class="mobile-card"><h3>原文批注</h3><blockquote>“只用指尖轻轻摸着信纸的边缘”</blockquote><p>用动作承载情感，细节真实自然。</p></div><p class="mobile-note">本次批改已完成，无需再次提交。{{record.status==='已复核'?'老师正在复核修订，当前仍显示上次正式成绩。':''}}</p></template>
  <template v-else><div class="mobile-card"><h3>写作要求</h3><p class="feedback-copy">{{current.description}}</p><div class="mobile-rule"><Icon name="SafetyCertificateOutlined"/>{{current.rule.name}}<small>{{current.rule.dimensions.map(d=>d.name+d.max).join(' · ')}}</small></div></div>
   <template v-if="canSubmit"><div class="mobile-section-head"><h3>{{record.status==='需补交'?'补齐原稿图片':'我的提交'}}</h3><span>{{photos.length}} 页</span></div><div class="mobile-upload" v-if="!photos.length"><Icon name="CameraOutlined"/><h3>{{record.status==='需补交'?'补拍缺页或模糊页面':'拍下你的作文'}}</h3><p>拍摄完整页面，保持文字清晰</p><a-upload :before-upload="pick" multiple :show-upload-list="false" accept="image/*"><a-button type="primary">选择作文照片</a-button></a-upload><a-button type="link" @click="sample">拍摄作文</a-button></div><template v-else><div v-for="(p,i) in photos" :key="p.id" class="photo-row"><img v-if="p.url" :src="p.url" alt="作文页面预览"/><div v-else class="photo-placeholder"><Icon name="FileTextOutlined"/></div><div><strong>第 {{i+1}} 页</strong><small>{{p.name}}</small><a-space><a-button size="small" :disabled="i===0" @click="move(i,-1)">上移</a-button><a-button size="small" :disabled="i===photos.length-1" @click="move(i,1)">下移</a-button><a-button size="small" danger @click="photos.splice(i,1)">删除</a-button></a-space></div></div><a-button block type="primary" :loading="busy" @click="submit">确认提交 · {{photos.length}} 页</a-button></template><p class="mobile-note">确认照片完整、页序正确后提交。老师复核完成后可查看反馈。</p></template>
   <div v-else class="mobile-status-card"><Icon name="CheckCircleOutlined"/><h3>作文已收到</h3><p>{{record.source}} · {{record.pages}} 页</p><a-steps direction="vertical" size="small" :current="2" :items="[{title:'提交成功'},{title:'AI 初评完成'},{title:'等待老师复核与发布'}]"/><small>无需重复提交，老师发布后即可查看反馈。</small></div>
  </template>
 </template>
 </div><nav class="phone-nav"><button v-for="[label,icon] in [['任务','FileTextOutlined'],['消息','BellOutlined'],['我的','UserOutlined']]" :class="{active:ui.appPage===label}" @click="ui.appPage=label;ui.appDetail=false"><Icon :name="icon"/>{{label==='任务'?'作文任务':label}}</button></nav><div class="home-indicator"></div></div><div class="phone-caption">中文路 · 学生端</div></div>
</main></template>
