<script setup>
import {computed,ref} from 'vue'
import {message} from 'ant-design-vue'
import {db,ui,task,original,log,defaultInput} from './store'
import Icon from './Icon.vue'
const emit=defineEmits(['close']);const batch=ref([]),busy=ref(false)
const current=task();const candidates=computed(()=>db.students.map(s=>({value:s.id,label:`${s.number}号 ${s.name}`})))
function demo(){const targets=db.submissions.filter(r=>r.taskId===current.id&&['未提交','需补交'].includes(r.status));batch.value=targets.map((r,i)=>({key:Date.now()+i,name:`作文扫描_${i+1}.pdf`,pages:3,studentId:i===1?undefined:r.studentId}));if(!targets.length)message.info('本任务已全部收稿。可上传文件检查重复稿件。')}
function add(file){if(!/\.(jpg|jpeg|png|webp|pdf)$/i.test(file.name)){message.warning('请选择图片或 PDF');return false}batch.value.push({key:Date.now()+Math.random(),name:file.name,pages:1,studentId:undefined});return false}
function state(row){if(!row.studentId)return '待匹配';if(batch.value.filter(r=>r.studentId===row.studentId).length>1)return '批次内重复';const r=db.submissions.find(r=>r.taskId===current.id&&r.studentId===row.studentId);return r?.status==='需补交'?'补齐原稿':r?.status==='未提交'?'已匹配':'已有稿件'}
const valid=computed(()=>batch.value.length>0&&batch.value.every(r=>['已匹配','补齐原稿'].includes(state(r))&&Number.isInteger(r.pages)&&r.pages>0))
async function submit(){if(!valid.value)return message.warning('请先解决学生匹配或重复稿件');busy.value=true;await new Promise(r=>setTimeout(r,650));for(const row of batch.value){const r=db.submissions.find(r=>r.taskId===current.id&&r.studentId===row.studentId);Object.assign(r,{status:'待复核',source:'老师批量上传',pages:row.pages,input:defaultInput(r.studentId),files:[{name:row.name}],feedback:'AI 初评：文章围绕题意展开，建议增加具体细节与心理变化。',review:null});log(`批量收稿：${db.students.find(s=>s.id===row.studentId)?.name}，${row.pages}页`)}message.success('识别与初评已完成，稿件进入待复核');busy.value=false;emit('close')}
</script>
<template><a-drawer :open="true" title="批量上传与学生匹配" width="800" @close="emit('close')"><a-steps size="small" :current="batch.length?1:0" :items="[{title:'上传文件'},{title:'确认归属'},{title:'AI 初评'}]"/><a-alert style="margin:24px 0" message="上传后请确认学生归属与页序。同名、缺页及重复稿件需处理后才能批改。" type="info" show-icon/><div class="upload-zone"><Icon name="CloudUploadOutlined"/><h3>上传学生作文照片或扫描文件</h3><p>支持多文件 · 一个学生可包含多页</p><a-space><a-upload multiple :before-upload="add" :show-upload-list="false" accept="image/jpeg,image/png,image/webp,application/pdf"><a-button type="primary">选择本地文件</a-button></a-upload><a-button @click="demo">从扫描记录导入</a-button></a-space></div><div class="panel-head" style="margin-top:28px"><h3>{{current.title}}</h3><span class="muted">{{batch.length}}份待确认</span></div><a-empty v-if="!batch.length" description="请先选择文件或从扫描记录导入"/><div v-for="r in batch" :key="r.key" class="batch-row"><div class="batch-file"><Icon name="FilePdfOutlined"/><strong>{{r.name}}</strong><a-button type="text" danger @click="batch=batch.filter(x=>x.key!==r.key)"><Icon name="DeleteOutlined"/></a-button></div><div class="batch-fields"><a-select v-model:value="r.studentId" placeholder="选择学生" :options="candidates" style="width:210px"/><a-input-number v-model:value="r.pages" :min="1" :max="30" :precision="0" addon-after="页"/><a-tag :color="['已匹配','补齐原稿'].includes(state(r))?'green':'orange'">{{state(r)}}</a-tag></div><small v-if="state(r)==='已有稿件'" class="warning-text">已有有效稿件，请移除本项避免重复。已评分原稿修订须单独复核。</small></div><template #footer><div class="review-footer"><span class="muted">确认后同步更新学生 App 收稿状态</span><a-button type="primary" :disabled="!valid" :loading="busy" @click="submit">确认收稿并批改</a-button></div></template></a-drawer></template>
